-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgd/DAlATZtpyzd4Ld
V2pOfSNWz7xxbXwZyA1xhu+SnpugCgYIKoZIzj0DAQehRANCAATA7z6pMLXXRJKg
ABTTWNRIIDy8p2A7DQnslgJv7sbdSi3526FfazcfwhqlMNmDBnio5GL+oJ+mqNO1
UIWzd3jL
-----END PRIVATE KEY-----